const RECORDS_KEY="twilight-life-log-v1";
const SETTINGS_KEY="twilight-life-log-settings-v1";
const DEFAULT_PROMPT="你是一位温柔、克制的生活记录整理者。请根据用户今天的碎片记录，写一段简短的中文日记式总结。不要捏造事实。可用【今日片段】【心情或感受】【值得留意】三个小标题；如果没有相应内容请自然省略。长度控制在 180 字以内。";
const $=s=>document.querySelector(s);
const state={records:read(RECORDS_KEY,{}),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:key(new Date())};
function key(d){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}
function read(name,fallback){try{return JSON.parse(localStorage.getItem(name))||fallback}catch{return fallback}}
function save(){localStorage.setItem(RECORDS_KEY,JSON.stringify(state.records))}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c]))}
function notify(message){const t=$("#toast");t.textContent=message;t.classList.add("show");clearTimeout(notify.id);notify.id=setTimeout(()=>t.classList.remove("show"),2600)}
function show(view){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===view));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===view))}
function recordToday(){return state.records[key(new Date())]||{entries:[],summary:null}}
function dateLabel(k){return new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(new Date(k+"T12:00:00"))}
function rich(text){return escapeHtml(text).replace(/\n/g,"<br>").replace(/【(.+?)】/g,"<strong>【$1】</strong>")}

function renderToday(){const r=recordToday(),list=$("#entry-list");$("#today-count").textContent=`${r.entries.length} 条`;if(!r.entries.length){list.className="empty";list.textContent="还没有记录。先给今天留下一句话吧。"}else{list.className="entry-list";list.innerHTML=r.entries.map(e=>`<article class="entry"><time>${escapeHtml(e.time)}</time><div class="entry-text">${escapeHtml(e.text)}</div><button class="delete" data-id="${e.id}" title="删除">×</button></article>`).join("")}const s=$("#summary-content");if(r.summary){s.className="summary";s.innerHTML=`${rich(r.summary.text)}<p class="summary-meta">整理于 ${r.summary.time}</p>`}else{s.className="summary empty-copy";s.textContent="当你留下几条生活碎片后，AI 会把它们温柔地整理成今天的回忆。"}}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$("#month-title").textContent=`${y} 年 ${m+1} 月`;let html="";for(let i=0;i<new Date(y,m,1).getDay();i++)html+='<div class="day empty-day"></div>';const today=key(new Date());for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const k=key(new Date(y,m,d)),r=state.records[k],c=["day",k===today?"today":"",r?.entries?.length?"has-entry":"",k===state.selected?"selected":""].filter(Boolean).join(" ");html+=`<button class="${c}" data-date="${k}">${d}</button>`}$("#calendar-grid").innerHTML=html;const r=state.records[state.selected],out=$("#selected-day-detail");if(!r?.entries?.length){out.className="empty detail";out.textContent=`${dateLabel(state.selected)}还没有留下记录。`}else{out.className="day-detail";out.innerHTML=`<h3>${dateLabel(state.selected)}</h3><ul>${r.entries.map(e=>`<li>${escapeHtml(e.text)}</li>`).join("")}</ul>${r.summary?`<div class="day-summary"><strong>AI 整理</strong><br>${rich(r.summary.text)}</div>`:""}`}}
function renderReview(){const days=Object.entries(state.records).filter(([,r])=>r.entries?.length).sort(([a],[b])=>b.localeCompare(a)),total=days.reduce((n,[,r])=>n+r.entries.length,0),recent=days.filter(([d])=>Date.now()-new Date(d+"T12:00:00")<6048e5),last=days[0];$("#review-content").innerHTML=`<article class="stat"><span>累计记录</span><strong>${total}</strong><span>个生活碎片</span></article><article class="stat"><span>有记录的日子</span><strong>${days.length}</strong><span>天</span></article><article class="stat"><span>最近 7 天</span><strong>${recent.length}</strong><span>天有留下痕迹</span></article><article class="note"><p class="eyebrow">RECENTLY</p><h2>${last?"最近的一天":"从今天开始"}</h2><p>${last?`${dateLabel(last[0])}，你留下了 ${last[1].entries.length} 条生活碎片。`:"第一句记录，会成为这本生活日志的开端。"}</p></article>`}
function render(){renderToday();renderCalendar();renderReview()}

$("#entry-form").addEventListener("submit",e=>{e.preventDefault();const text=$("#entry-input").value.trim();if(!text)return $("#entry-input").focus();const k=key(new Date()),now=new Date();if(!state.records[k])state.records[k]={entries:[],summary:null};state.records[k].entries.unshift({id:crypto.randomUUID(),text,time:now.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})});state.records[k].summary=null;save();$("#entry-input").value="";$("#character-count").textContent="0 / 1000";render();notify("已把这一刻收好")});
$("#entry-input").addEventListener("input",e=>$("#character-count").textContent=`${e.target.value.length} / 1000`);
$("#entry-list").addEventListener("click",e=>{const id=e.target.dataset.id;if(!id)return;const k=key(new Date()),r=state.records[k];r.entries=r.entries.filter(x=>x.id!==id);if(r.entries.length)r.summary=null;else delete state.records[k];save();render();notify("已删除这条记录")});
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>show(b.dataset.view)));const settingsMenu=$("#settings-menu");$("#settings-button").addEventListener("click",e=>{e.stopPropagation();settingsMenu.classList.toggle("open")});document.querySelectorAll("[data-settings-target]").forEach(b=>b.addEventListener("click",()=>{show("settings-view");settingsMenu.classList.remove("open");setTimeout(()=>document.getElementById(b.dataset.settingsTarget)?.scrollIntoView({behavior:"smooth",block:"start"}),0)}));document.addEventListener("click",e=>{if(!e.target.closest(".settings-menu-wrap"))settingsMenu.classList.remove("open")});
$("#previous-month").onclick=()=>{state.month.setMonth(state.month.getMonth()-1);renderCalendar()};$("#next-month").onclick=()=>{state.month.setMonth(state.month.getMonth()+1);renderCalendar()};$("#calendar-grid").addEventListener("click",e=>{const b=e.target.closest("[data-date]");if(b){state.selected=b.dataset.date;renderCalendar()}});

const saved=read(SETTINGS_KEY,{});$("#api-base-url").value=saved.baseUrl||"https://api.openai.com/v1";$("#api-key").value=saved.apiKey||"";$("#model-name").value=saved.model||"gpt-4o-mini";$("#system-prompt").value=saved.prompt||DEFAULT_PROMPT;
$("#settings-form").addEventListener("submit",e=>{e.preventDefault();localStorage.setItem(SETTINGS_KEY,JSON.stringify({baseUrl:$("#api-base-url").value.trim().replace(/\/$/,""),apiKey:$("#api-key").value.trim(),model:$("#model-name").value.trim(),prompt:$("#system-prompt").value.trim()||DEFAULT_PROMPT}));notify("AI 配置已保存在当前浏览器")});
$("#clear-settings").onclick=()=>{localStorage.removeItem(SETTINGS_KEY);$("#settings-form").reset();$("#system-prompt").value=DEFAULT_PROMPT;notify("已清除 AI 配置")};
$("#load-models").onclick=async()=>{const base=$("#api-base-url").value.trim().replace(/\/$/,""),apiKey=$("#api-key").value.trim(),button=$("#load-models");if(!base||!apiKey)return notify("请先填写 API 地址和 API Key");button.disabled=true;button.textContent="正在拉取…";try{const r=await fetch(base+"/models",{headers:{Authorization:`Bearer ${apiKey}`}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||`接口返回 ${r.status}`);const models=(d.data||d.models||[]).map(x=>typeof x==="string"?x:x.id).filter(Boolean);if(!models.length)throw Error("接口没有返回模型列表");$("#model-options").innerHTML=models.map(x=>`<option value="${escapeHtml(x)}"></option>`).join("");if(!$("#model-name").value)$("#model-name").value=models[0];notify(`已拉取 ${models.length} 个模型`)}catch(e){notify(`拉取失败：${e.message}`)}finally{button.disabled=false;button.textContent="拉取模型"}};
$("#summarize-button").onclick=async()=>{const r=recordToday(),config=read(SETTINGS_KEY,{}),button=$("#summarize-button");if(!r.entries.length)return notify("先留下一条生活记录吧");if(!config.baseUrl||!config.apiKey||!config.model){show("settings-view");return notify("请先完成 AI 配置")}button.disabled=true;button.textContent="正在整理…";try{const content=r.entries.slice().reverse().map(x=>`- ${x.text}`).join("\n"),res=await fetch(config.baseUrl+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${config.apiKey}`},body:JSON.stringify({model:config.model,temperature:.7,messages:[{role:"system",content:config.prompt||DEFAULT_PROMPT},{role:"user",content:`今天的原始记录：\n${content}`}]})}),data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error?.message||`接口返回 ${res.status}`);const text=data.choices?.[0]?.message?.content?.trim();if(!text)throw Error("AI 没有返回可用内容");r.summary={text,time:new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})};save();render();notify("AI 已整理好今天的记录")}catch(e){notify(`整理失败：${e.message}`)}finally{button.disabled=false;button.textContent="✦ 让 AI 整理"}};
$("#today-label").textContent=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(new Date());render();
