const RECORDS_KEY="twilight-life-log-v1",SETTINGS_KEY="twilight-life-log-settings-v1";
const DEFAULT_PROMPT="你是一位温柔、克制的生活记录整理者。请根据用户当天的文字与图片记录，写一段简短的中文日记式总结。不要捏造图片或文字中没有的信息。可用【今日片段】【心情或感受】【值得留意】三个小标题；如果没有相应内容请自然省略。长度控制在 180 字以内。";
const $=s=>document.querySelector(s),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},esc=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c]));
const dateKey=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)},label=d=>new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(new Date(d+"T12:00:00"));
const state={records:read(RECORDS_KEY,{}),month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:dateKey(new Date())};let mainImages=[],historyImages=[],editingId=null;
function save(){localStorage.setItem(RECORDS_KEY,JSON.stringify(state.records))}function notice(s){const t=$("#toast");t.textContent=s;t.classList.add("show");clearTimeout(notice.t);notice.t=setTimeout(()=>t.classList.remove("show"),2800)}function show(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===id));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id===id))}
function rec(day,create=false){if(create&&!state.records[day])state.records[day]={entries:[],summary:null};return state.records[day]||{entries:[],summary:null}}function imgs(e){return Array.isArray(e.images)?e.images:[]}function pics(a){return a.length?'<div class="saved-images">'+a.map(i=>'<img src="'+esc(i.data)+'" alt="日记图片" loading="lazy">').join("")+"</div>":""}function rich(s){return esc(s).replace(/\n/g,"<br>").replace(/【(.+?)】/g,"<strong>【$1】</strong>")}
function entryCard(e,day){return '<article class="entry"><time>'+esc(e.time||"")+'</time><div class="entry-text">'+esc(e.text||"")+pics(imgs(e))+'</div><div class="entry-tools"><button data-action="edit" data-date="'+day+'" data-id="'+e.id+'">编辑</button><button class="delete" data-action="delete" data-date="'+day+'" data-id="'+e.id+'">×</button></div></article>'}
function summary(r,target){if(r.summary){target.className="summary";target.innerHTML=rich(r.summary.text)+'<p class="summary-meta">整理于 '+r.summary.time+"</p>"}else{target.className="summary empty-copy";target.textContent="当你留下几条生活碎片后，AI 会把它们温柔地整理成今天的回忆。"}}
function renderToday(){const d=dateKey(new Date()),r=rec(d),list=$("#entry-list");$("#today-count").textContent=r.entries.length+" 条";if(r.entries.length){list.className="entry-list";list.innerHTML=r.entries.map(e=>entryCard(e,d)).join("")}else{list.className="empty";list.textContent="还没有记录。先给今天留下一句话吧。"}summary(r,$("#summary-content"))}
function renderSelected(){const r=rec(state.selected),o=$("#selected-day-detail");if(!r.entries.length){o.className="empty detail";o.textContent=label(state.selected)+"还没有留下记录。"}else{o.className="day-detail";o.innerHTML="<h3>"+label(state.selected)+'</h3><div class="day-entry-list">'+r.entries.map(e=>'<article class="day-entry"><div>'+esc(e.text||"")+pics(imgs(e))+'</div><div class="day-entry-tools"><button data-action="edit" data-date="'+state.selected+'" data-id="'+e.id+'">编辑</button><button data-action="delete" data-date="'+state.selected+'" data-id="'+e.id+'">删除</button></div></article>').join("")+'</div>'+(r.summary?'<div class="day-summary"><strong>AI 整理</strong><br>'+rich(r.summary.text)+"</div>":"")}$("#history-date").value=state.selected;$("#history-summarize").disabled=!r.entries.length;if(!editingId){$("#history-editor-title").textContent="补写 "+label(state.selected);$("#history-editor-copy").textContent="可以补写这一天的记录，也可以为它重新整理。"}}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$("#month-title").textContent=y+" 年 "+(m+1)+" 月";let h="";for(let i=0;i<new Date(y,m,1).getDay();i++)h+='<div class="day empty-day"></div>';const now=dateKey(new Date());for(let i=1;i<=new Date(y,m+1,0).getDate();i++){const d=dateKey(new Date(y,m,i)),r=rec(d),c=["day",d===now?"today":"",r.entries.length?"has-entry":"",d===state.selected?"selected":""].filter(Boolean).join(" ");h+='<button class="'+c+'" data-date="'+d+'">'+i+"</button>"}$("#calendar-grid").innerHTML=h;renderSelected()}
function renderReview(){const ds=Object.entries(state.records).filter(([,r])=>r.entries?.length).sort(([a],[b])=>b.localeCompare(a)),all=ds.reduce((n,[,r])=>n+r.entries.length,0),week=ds.filter(([d])=>Date.now()-new Date(d+"T12:00:00")<6048e5),last=ds[0];$("#review-content").innerHTML='<article class="stat"><span>累计记录</span><strong>'+all+'</strong><span>个生活碎片</span></article><article class="stat"><span>有记录的日子</span><strong>'+ds.length+'</strong><span>天</span></article><article class="stat"><span>最近 7 天</span><strong>'+week.length+'</strong><span>天有留下痕迹</span></article><article class="note"><h2>'+ (last?"最近的一天":"从今天开始")+"</h2><p>"+(last?label(last[0])+"，你留下了 "+last[1].entries.length+" 条生活碎片。":"第一句记录，会成为这本生活日志的开端。")+"</p></article>"}function render(){renderToday();renderCalendar();renderReview()}
function preview(scope){const a=scope==="main"?mainImages:historyImages,t=scope==="main"?$("#entry-image-preview"):$("#history-image-preview");t.innerHTML=a.map((i,n)=>'<div class="image-preview"><img src="'+esc(i.data)+'" alt="待保存图片"><button type="button" data-image-scope="'+scope+'" data-image-index="'+n+'">×</button></div>').join("")}
function pack(file){return new Promise((ok,bad)=>{if(!file.type.startsWith("image/"))return bad(Error("只能添加图片文件"));if(file.size>8*1024*1024)return bad(Error("单张图片不能超过 8MB"));const rd=new FileReader;rd.onerror=()=>bad(Error("图片读取失败"));rd.onload=()=>{const im=new Image;im.onerror=()=>bad(Error("此图片格式暂不支持"));im.onload=()=>{const r=Math.min(1,1600/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=im.width*r;c.height=im.height*r;c.getContext("2d").drawImage(im,0,0,c.width,c.height);ok({id:crypto.randomUUID(),name:file.name,data:c.toDataURL("image/jpeg",.82)})};im.src=rd.result};rd.readAsDataURL(file)})}
async function addPics(scope,files){const a=scope==="main"?mainImages:historyImages,n=3-a.length;if(n<=0)return notice("每条记录最多添加 3 张图片");try{a.push(...await Promise.all([...files].slice(0,n).map(pack)));preview(scope);if(files.length>n)notice("每条记录最多添加 3 张图片")}catch(e){notice(e.message)}}
function clearEditor(){editingId=null;historyImages=[];$("#history-entry-input").value="";$("#history-image-input").value="";$("#history-cancel-edit").hidden=true;$("#history-save").textContent="保存到这一天";preview("history");renderSelected()}
function store(day,text,images,id){if(!text&&!images.length)throw Error("请写点文字或添加一张图片");const r=rec(day,true);if(id){const e=r.entries.find(x=>x.id===id);if(e){e.text=text;e.images=images;e.updatedAt=new Date().toISOString()}}else r.entries.unshift({id:crypto.randomUUID(),text,images,time:new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"}),createdAt:new Date().toISOString()});r.summary=null;save();render()}
function edit(day,id){const e=rec(day).entries.find(x=>x.id===id);if(!e)return;state.selected=day;state.month=new Date(day+"T12:00:00");editingId=id;historyImages=imgs(e).map(x=>({...x}));$("#history-entry-input").value=e.text||"";$("#history-editor-title").textContent="编辑 "+label(day)+" 的记录";$("#history-editor-copy").textContent="保存后会替换原来的内容，并需要重新 AI 整理。";$("#history-cancel-edit").hidden=false;$("#history-save").textContent="保存修改";preview("history");show("calendar-view");renderCalendar();$("#history-entry-input").focus()}
function remove(day,id){const r=rec(day);r.entries=r.entries.filter(x=>x.id!==id);r.summary=null;if(!r.entries.length)delete state.records[day];save();if(editingId===id)clearEditor();render();notice("已删除这条记录")}
function aiContent(entries){const text=entries.slice().reverse().map(e=>"- "+(e.text||"（一张图片）")).join("\n"),all=entries.slice().reverse().flatMap(imgs);return all.length?[{type:"text",text:"当天的原始记录：\n"+text+"\n\n以下图片属于当天记录，请只描述看得见的内容。"},...all.map(i=>({type:"image_url",image_url:{url:i.data}}))]:"当天的原始记录：\n"+text}
async function summarize(day){const r=rec(day),cfg=read(SETTINGS_KEY,{}),today=day===dateKey(new Date()),b=today?$("#summarize-button"):$("#history-summarize");if(!r.entries.length)return notice("这一天还没有记录");if(!cfg.baseUrl||!cfg.apiKey||!cfg.model){show("settings-view");return notice("请先完成 AI 配置")}b.disabled=true;b.textContent="正在整理…";try{const res=await fetch(cfg.baseUrl.replace(/\/$/,"")+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+cfg.apiKey},body:JSON.stringify({model:cfg.model,temperature:.7,messages:[{role:"system",content:cfg.prompt||DEFAULT_PROMPT},{role:"user",content:aiContent(r.entries)}]})}),data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error?.message||"接口返回 "+res.status);const text=data.choices?.[0]?.message?.content?.trim();if(!text)throw Error("AI 没有返回可用内容");r.summary={text,time:new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})};save();render();notice("AI 已整理好 "+label(day))}catch(e){notice("整理失败："+e.message)}finally{b.disabled=false;b.textContent=today?"✦ 让 AI 整理":"✦ 整理这一天"}}
$("#entry-form").addEventListener("submit",e=>{e.preventDefault();try{store(dateKey(new Date()),$("#entry-input").value.trim(),mainImages);$("#entry-input").value="";$("#character-count").textContent="0 / 1000";mainImages=[];preview("main");notice("已把这一刻收好")}catch(x){notice(x.message)}});$("#entry-input").addEventListener("input",e=>$("#character-count").textContent=e.target.value.length+" / 1000");
$("#add-image-button").onclick=()=>$("#entry-image-input").click();$("#entry-image-input").onchange=e=>{addPics("main",e.target.files);e.target.value=""};$("#history-add-image").onclick=()=>$("#history-image-input").click();$("#history-image-input").onchange=e=>{addPics("history",e.target.files);e.target.value=""};
$("#history-entry-form").addEventListener("submit",e=>{e.preventDefault();try{store($("#history-date").value,$("#history-entry-input").value.trim(),historyImages,editingId);notice(editingId?"已保存修改":"已补写这一天的记录");clearEditor()}catch(x){notice(x.message)}});$("#history-date").onchange=e=>{if(e.target.value){state.selected=e.target.value;state.month=new Date(e.target.value+"T12:00:00");clearEditor();renderCalendar()}};$("#history-cancel-edit").onclick=clearEditor;$("#history-summarize").onclick=()=>summarize(state.selected);
document.addEventListener("click",e=>{const x=e.target.closest("[data-image-scope]");if(x){const a=x.dataset.imageScope==="main"?mainImages:historyImages;a.splice(+x.dataset.imageIndex,1);preview(x.dataset.imageScope);return}const a=e.target.closest("[data-action]");if(a)a.dataset.action==="edit"?edit(a.dataset.date,a.dataset.id):remove(a.dataset.date,a.dataset.id)});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>show(b.dataset.view));const menu=$("#settings-menu");$("#settings-button").onclick=e=>{e.stopPropagation();menu.classList.toggle("open")};document.querySelectorAll("[data-settings-target]").forEach(b=>b.onclick=()=>{show("settings-view");menu.classList.remove("open");setTimeout(()=>document.getElementById(b.dataset.settingsTarget)?.scrollIntoView({behavior:"smooth"}))});document.addEventListener("click",e=>{if(!e.target.closest(".settings-menu-wrap"))menu.classList.remove("open")});$("#previous-month").onclick=()=>{state.month.setMonth(state.month.getMonth()-1);renderCalendar()};$("#next-month").onclick=()=>{state.month.setMonth(state.month.getMonth()+1);renderCalendar()};$("#calendar-grid").onclick=e=>{const b=e.target.closest("[data-date]");if(b){state.selected=b.dataset.date;clearEditor();renderCalendar()}};
const cfg=read(SETTINGS_KEY,{});$("#api-base-url").value=cfg.baseUrl||"https://api.openai.com/v1";$("#api-key").value=cfg.apiKey||"";$("#model-name").value=cfg.model||"gpt-4o-mini";$("#system-prompt").value=cfg.prompt||DEFAULT_PROMPT;$("#settings-form").onsubmit=e=>{e.preventDefault();localStorage.setItem(SETTINGS_KEY,JSON.stringify({baseUrl:$("#api-base-url").value.trim().replace(/\/$/,""),apiKey:$("#api-key").value.trim(),model:$("#model-name").value.trim(),prompt:$("#system-prompt").value.trim()||DEFAULT_PROMPT}));notice("AI 配置已保存在当前浏览器")};$("#clear-settings").onclick=()=>{localStorage.removeItem(SETTINGS_KEY);$("#settings-form").reset();$("#system-prompt").value=DEFAULT_PROMPT;notice("已清除 AI 配置")};$("#load-models").onclick=async()=>{const base=$("#api-base-url").value.trim().replace(/\/$/,""),key=$("#api-key").value.trim(),b=$("#load-models");if(!base||!key)return notice("请先填写 API 地址和 API Key");b.disabled=true;b.textContent="正在拉取…";try{const r=await fetch(base+"/models",{headers:{Authorization:"Bearer "+key}}),d=await r.json();if(!r.ok)throw Error(d.error?.message||"接口返回 "+r.status);const m=(d.data||d.models||[]).map(x=>typeof x==="string"?x:x.id).filter(Boolean);$("#model-options").innerHTML=m.map(x=>'<option value="'+esc(x)+'"></option>').join("");if(!$("#model-name").value)$("#model-name").value=m[0];notice("已拉取 "+m.length+" 个模型")}catch(e){notice("拉取失败："+e.message)}finally{b.disabled=false;b.textContent="拉取模型"}};$("#summarize-button").onclick=()=>summarize(dateKey(new Date()));$("#today-label").textContent=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(new Date());render();
